name: Build Artifacts

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Build (assemble)
        run: ./gradlew --no-daemon clean assemble

      - name: Upload jars (build/libs)
        uses: actions/upload-artifact@v4
        with:
          name: app-jars
          path: build/libs/*
