name: CI
on:
  push: { branches: [ main, dev ] }
  pull_request: { branches: [ main, dev ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '21' }
      - name: Build & Test
        run: ./gradlew check --no-daemon
